- name: deploy l4d2 server
  sudo: true
  hosts: box1
  vars:
    docker_repo_url: "https://apt.dockerproject.org/repo"
    docker_key_server: "hkp://p80.pool.sks-keyservers.net:80"
    docker_key_id: "58118E89F3A912897C070ADBF76221572C52609D"
  tasks:
    #- debug: var=hostvars[inventory_hostname]
    - name: update apt cache
      apt: update_cache="true"

    - name: install docker repo apt key deps
      apt: state="present" name="{{ item }}"
      with_items:
        - apt-transport-https
        - ca-certificates

    - name: add docker repo apt key
      apt_key: keyserver="{{ docker_key_server }}" id="{{ docker_key_id }}"

    - name: add docker repo
      template: src="templates/docker.list.j2" dest="/etc/apt/sources.list.d/docker.list"

    - name: add extra kernel modules
      shell: apt-get -y install linux-image-extra-$(uname -r)

    - name: get apparmor
      apt: update_cache="true" state="present" name="apparmor"

    - name: install docker
      apt: state="present" name="docker-engine"

    - name: start and enable docker service
      service: name="docker" enabled="true" state="started"

    - name: install python & pip
      apt: state="present" name="{{ item }}"
      with_items:
          - python
          - python-pip

    - name: install docker py for use by ansible module
      pip: name="docker-py"

    - name: create server container
      docker_container:
        name: "l4d2_server"
        image: "snipzwolf/l4d2-server"
        restart_policy: "always"
        ports:
          - "27015:27015"
          - "27016:27016"
          - "27017:27017"
          - "27018:27018"
          - "27019:27019"
          - "27020:27020"
          - "27015:27015/udp"
          - "27016:27016/udp"
          - "27017:27017/udp"
          - "27018:27018/udp"
          - "27019:27019/udp"
          - "27020:27020/udp"
